Default: &defaults
  database: eager.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: eager_test.sqlite3
  <<: *defaults

Staging:
  database: eager_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: eager_production.sqlite3
  poolsize: 100
  <<: *defaults
